"""loan_user

Revision ID: c22b0d09db58
Revises: fe3ca2ddb6fe
Create Date: 2026-01-13 14:58:32.227170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c22b0d09db58'
down_revision: Union[str, None] = 'fe3ca2ddb6fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('loanees_user_id_key'), 'loanees', type_='unique')
    op.drop_constraint(op.f('loanees_user_id_fkey'), 'loanees', type_='foreignkey')
    op.drop_column('loanees', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loanees', sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('loanees_user_id_fkey'), 'loanees', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(op.f('loanees_user_id_key'), 'loanees', ['user_id'])
    # ### end Alembic commands ###
