"""document_uploaded

Revision ID: f1000e8f3cd9
Revises: c22b0d09db58
Create Date: 2026-01-15 12:56:57.266250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1000e8f3cd9'
down_revision: Union[str, None] = 'c22b0d09db58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('is_document_uploaded', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'is_document_uploaded')
    # ### end Alembic commands ###
